#######################################################################################################################################################
; Kunsztowny mithrylowy topor bojowy
; Aktualizacja: 20.02.11
; Ja kogoś

/def -p200 -mregexp -t'Przy wtorze swistu powietrza (.*) uskakuje przed morderczym ciosem twojego kunsztownego mithrylowego topora bojowego\.' _mithryl_ja_kogos_unik = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 0/6] @{Cyellow}@{BCwhite}probuje specowac @{Cblue}%{P1} @{Cwhite}(unik).
/def -p200 -mregexp -t'Twoj kunsztowny mithrylowy topor bojowy dotyka (.*) w (.*) robiac ladna, swieza rane\.' _mithryl_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 1/6] @{Cyellow}@{BCwhite}specuje @{Cblue}%{P1} @{Cwhite}(%{P2}).
/def -p200 -mregexp -t'Dobrze wymierzonym ciosem swego kunsztownego mithrylowego topora bojowego rabiesz (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape) (.*)\.' _mithryl_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 2/6] @{Cyellow}@{BCwhite}specuje @{Cblue}%{P2} @{Cwhite}(%{P1}).
/def -p200 -mregexp -t'Swoim kunsztownym mithrylowym toporem bojowym tniesz gleboko (.*) w (.*), a do twych uszu dochodzi zgrzyt ostrza o kosci\.' _mithryl_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 3/6] @{Cyellow}@{BCwhite}specuje @{Cblue}%{P1} @{Cwhite}(%{P2}).
/def -p200 -mregexp -t'Tniesz gleboko swym kunsztownym mithrylowym toporem bojowym w (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape) (.*) i slyszysz glosny odglos druzgotanych kosci\.' _mithryl_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 4/6] @{Cyellow}@{BCwhite}specuje @{Cblue}%{P2} @{Cwhite}(%{P1}).
/def -p200 -mregexp -t'(.*) niemal przewraca sie pod impetem twojego ciosu, gdy twoj kunsztowny mithrylowy topor bojowy trafia [^ ]+ w (.*)\.' _mithryl_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 5/6] @{Cyellow}@{BCwhite}specuje @{Cblue}%{P1} @{Cwhite}(%{P2}).
/def -p200 -mregexp -t'Twoj kunsztowny mithrylowy topor bojowy brutalnie druzgocze (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape) (.*) ze smiercionosna sila. (.*) pada na ziemie jako zmasakrowane i niemal nierozpoznawalne cialo\.' _mithryl_ja_kogos_6 = /substitute -p @{BCwhite}----> @{Cyellow}[Mithryl 6/6] @{Cyellow}@{BCwhite}specuje @{Cblue}%{P2} @{Cwhite}(%{P1}).

; Ktoś mnie
/def -p200 -mregexp -t'Przy wtorze swistu powietrza uskakujesz przed morderczm ciosem kunsztownego mithrylowego topora bojowego, zadanym przez (.*)\.' _mithryl_ktos_mnie_unik = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 0/6] @{BCwhite}proba speca @{Cyellow}%{P1} @{Cwhite}w @{Cblue}cie @{Cwhite}(unik).
; 1 działa z 'Ktoś kogoś'
/def -p200 -mregexp -t'Dobrze wymierzonym ciosem swego kunsztownego mithrylowego topora bojowego (.*) rabie cie w (.*)\.' _mithryl_ktos_mnie_2 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 2/6] @{Cyellow}%{P1} @{BCwhite}specuje @{Cblue}cie @{Cwhite}(%{P2}).

; Ktoś kogoś
/def -p200 -mregexp -t'Przy wtorze swistu powietrza (.*) uskakuje przed morderczym ciosem kunsztownego mithrylowego topora bojowego, zadanym przez (.*)\.' _mithryl_ktos_kogos_unik = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 0/6] @{BCwhite}proba speca @{Cyellow}%{P2} @{Cwhite}w @{Cblue}%{P1} @{Cwhite}(unik).
/def -p200 -mregexp -t'Kunsztowny mithrylowy topor bojowy (.*) dotyka (.*) w (.*) robiac ladna, swieza rane\.' _mithryl_ktos_kogos_1 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 1/6] @{BCwhite}spec @{Cyellow}%{P1} @{Cwhite}w @{Cblue}%{P2} @{Cwhite}(%{P3}).
/def -p200 -mregexp -t'Dobrze wymierzonym ciosem swego kunsztownego mithrylowego topora bojowego (.*) rabie (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape) (.*)\.' _mithryl_ktos_kogos_2 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 2/6] @{Cyellow}%{P1} @{BCwhite}specuje @{Cblue}%{P3} @{Cwhite}(%{P2}).
/def -p200 -mregexp -t'Swoim kunsztownym mithrylowym toporem bojowym (.*) tnie gleboko (.*) w (.*), a do twych uszu dochodzi zgrzyt ostrza o kosci\.' _mithryl_ktos_kogos_3 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 3/6] @{Cyellow}%{P1} @{BCwhite}specuje @{Cblue}%{P2} @{Cwhite}(%{P3}).
/def -p200 -mregexp -t' tnie gleboko w (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape) (.*), a ty slyszysz glosny odglos druzgotanych kosci\.' _mithryl_ktos_kogos_4 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 4/6] @{Cyellow}%{PL} @{BCwhite}specuje @{Cblue}%{P2} @{Cwhite}(%{P1}).
/def -p200 -mregexp -t'(.*) niemal przewraca sie pod impetem ciosu, gdy kunsztowny mithrylowy topor bojowy (.*) trafia [^ ]+ w (.*)\.' _mithryl_ktos_kogos_5 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 5/6] @{BCwhite}spec @{Cyellow}%{P2} @{Cwhite}w @{Cblue}%{P1} @{Cwhite}(%{P3}).
/def -p200 -mregexp -t'Kunsztowny mithrylowy topor bojowy (.*) brutalnie druzgocze (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape) (.*) ze smiercionosna sila. (.*) pada na ziemie jako zmasakrowane i niemal nierozpoznawalne cialo\.' _mithryl_ktos_kogos_6 = /substitute -p @{BCwhite}-------> @{Cyellow}[Mithryl 6/6] @{BCwhite}spec @{Cyellow}%{P1} @{BCwhite}w @{Cblue}%{P3} @{Cwhite}(%{P2}).

#######################################################################################################################################################

; Ciezki zdobiony topor
; Aktualizacja: 20.07.11
; Ja kogoś

/def -p200 -mregexp -t'Bierzesz plynny zamach swoim ciezkim zdobionym toporem w (.*) jednak przeciwnik wykonuje zgrabny zwod i unika niecelnego ciosu.' _ciezki_zdobiony_ja_kogos_unik = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 0/7] @{BCwhite}proba ciosu w @{Cblue}%{P1} @{Cwhite}(unik).
/def -p200 -mregexp -t'Uderzenie twojego ciezkiego zdobionego topora pozostawia na ciele (.*) dluga, czerwona szrame.' _ciezki_zdobiony_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 1/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Ukosne ciecie twojego ciezkiego zdobionego topora pozostawia na ciele (.*) paskudna, krwawiaca szrame.' _ciezki_zdobiony_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 2/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Silnym wymachem swojego ciezkiego zdobionego topora trafiasz (.*) w (.*) pozostawiajac na (jego|jej) ciele niewielka rane.' _ciezki_zdobiony_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 3/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Trafiasz (.*) mocnym ciosem swojego ciezkiego zdobionego topora w (.*) raniac (go|ja) znacznie.' _ciezki_zdobiony_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 4/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Wykorzystujac chwile nieuwagi (.*) uderzasz poteznie swoim ciezkim zdobionym toporem tnac w (.*), by okrutnie rozerwac (jego|jej) tkanki.' _ciezki_zdobiony_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 5/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Szybkim ciosem swojego zdobionego topora trafiasz (.*) w (.*) niemal pozbawiajac (go|ja) zycia. Nastepny taki cios moze zakonczyc walke.' _ciezki_zdobiony_ja_kogos_6 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 6/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Dopadasz do (.*) i poteznie uderzajac od dolu swoim ciezkim zdobionym toporem tniesz (go|ja) w (.*), nie szczedzac nawet kosci. Zmasakrowane cialo pada na ziemie by znieruchomiec na zawsze.' _ciezki_zdobiony_ja_kogos_7 = /substitute -p @{BCwhite}----> @{Cyellow}[Zdobiony 7/7] @{BCwhite}cios w @{Cblue}%{P1}@{Cwhite}.

#######################################################################################################################################################

; Gwiezdny topor
; Aktualizacja: 21.07.11
; Ja kogoś

/def -p200 -mregexp -t'Bierzesz zamach i nieudolnie kierujac blyszczacym ostrzem gwiezdnego topora, chybiasz (.*) czujac irytacje poteg zakletych w broni.' _gwiazdka_ja_kogos_pudlo = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 0/5] @{BCwhite}probuje specowac @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Wyprowadzasz potezny cios swym gwiezdnym toporem w (.*), a niewielki blysk swiatla swiadczy, ze zaledwie drasnales (.*).' _gwiazdka_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 1/5] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'Swist i blysk rozpraszanej energii towarzysza uderzeniu w (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape|metalowy korpus|pobruzdzona glowe|cienki szczekoczulek|kamienny korpus|plamiasta glowe|umiesnione prawe ramie|umiesnione lewe ramie|pysk|widmowe nogi) (.*) twym gwiezdnym toporem mimo, iz zadales niewielkie obrazenia.' _gwiazdka_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 2/5] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'Blask tysiecy gwiazd i glosny swist towarzysza szybkiemu jak mysl ruchowi twej reki, ktory godzi w (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape|metalowy korpus|pobruzdzona glowe|cienki szczekoczulek|kamienny korpus|plamiasta glowe|umiesnione prawe ramie|umiesnione lewe ramie|pysk|widmowe nogi) (.*) gwiezdnym toporem, zadajac spore obrazenia i zalewajac ostrze posoka.' _gwiazdka_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 3/5] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'Plynnym kolistym ruchem godzisz (.*) swym gwiezdnym toporem trafiajac go w (.*). Czujesz, ze twoja bron zadala duze obrazenia, zalewajac twa twarz ciepla posoka.' _gwiazdka_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 4/5] @{BCwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Lsniace ostrze twego gwiezdnego topora zakresla szeroki luk, blyskawicznie godzac w (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape|metalowy korpus|pobruzdzona glowe|cienki szczekoczulek|kamienny korpus|plamiasta glowe|umiesnione prawe ramie|umiesnione lewe ramie|pysk|widmowe nogi) (.*), a fontanna swietlistej energii tryska z rany niczym posoka, zadajac ogromne obrazenia.' _gwiazdka_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 5/5] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.

; Akutalizacja: 05.11.12
; Ktoś kogoś
/def -p200 -mregexp -t' bierze zamach i nieudolnie kierujac blyszczacym ostrzem gwiezdnego topora, chybia (.*).' _gwiazdka_ktos_kogos_pudlo = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 0/5] @{Cyellow}%{PL} @{BCwhite}probuje specowac @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' wyprowadza potezny cios swym gwiezdnym toporem w (.*), a niewielki blysk swiatla swiadczy, ze zaledwie (drasnela|drasnal) (.*).' _gwiazdka_ktos_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 1/5] @{Cyellow}%{PL} @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Swist i blysk rozpraszanej energii towarzysza uderzeniu gwiezdnego topora (.*) w %{hitlocs} (.*) mimo, iz (zadal|zadala) niewielkie obrazenia.' _gwiazdka_ktos_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 2/5] @{Cyellow}%%{P1} @{BCwhite}specuje @{Cblue}%%{P3}@{Cwhite}.
/eval /def -p200 -mregexp -t'Blask tysiecy gwiazd i glosny swist towarzysza szybkiemu jak mysl ruchowi reki (.*), ktory godzi w %{hitlocs} (.*) gwiezdnym toporem, zadajac spore obrazenia i zalewajac ostrze posoka.' _gwiazdka_ktos_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 3/5] @{Cyellow}%%{P1} @{BCwhite}specuje @{Cblue}%%{P3}@{Cwhite}.
/def -p200 -mregexp -t' plynnym kolistym ruchem godzi (.*) swym gwiezdnym toporem trafiajac [^ ]+ w (.*). Duze obrazenia zadane przez bron, zalewaja twarz (.*) ciepla posoka.' _gwiazdka_ktos_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 4/5] @{Cyellow}%{PL} @{BCwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/eval /def -p200 -mregexp -t'Lsniace ostrze gwiezdnego topora (.*) zakresla szeroki luk, blyskawicznie godzac %{hitlocs} (.*), a fontanna swietlistej energii tryska z rany niczym posoka, zadajac ogromne obrazenia.' _gwiazdka_ktos_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Gwiazdka 5/5] @{Cyellow}%%{P1} @{BCwhite}specuje @{Cblue}%%{P3}@{Cwhite}.

#######################################################################################################################################################

; Zabkowany zakrzywiony sztylet
; Aktualizacja: 21.07.11
; Ktoś kogoś

/def -p200 -mregexp -t' trafia (.*) w (.*), delikatnie znaczac koncem ostrza swego sztyletu krwawa prege na (jego|jej) skorze.' _zabkowany_ktos_kogos_1 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 1/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' trafia (.*) w (.*), znaczac ostrzem swego sztyletu, krwawa bruzde na (jego|jej) ciele.' _zabkowany_ktos_kogos_2 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 2/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' trafia (.*) zabkowanym zakrzywionym sztyletem w (.*), znaczac ostrzem na jego ciele krwawa bruzde o poszarpanych brzegach.' _zabkowany_ktos_kogos_3 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 3/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' trafia (.*) zabkowanym zakrzywionym sztyletem raniac (go|ja|je) dotkliwie w (.*).' _zabkowany_ktos_kogos_4 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 4/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' wbija zabkowany zakrzywiony sztylet w (cialo|ogonek|prawe ramie|lewe ramie|pokryty twarda skora tulow|twarda glowe|kosmaty tulow|luskowate cialo|szponiaste rece|kosciane nogi|oslizgle cialo|lewa reke|prawa reke|lewa noge|prawa noge|glowe|korpus|nogi|tulow|leb|kudlate cialo|kamienna reke|jedna z lian|okolice korzeni|tors|lepek|kudlate cielsko|prawa lape|lewa lape|metalowy korpus|pobruzdzona glowe|cienki szczekoczulek|kamienny korpus|plamiasta glowe|umiesnione prawe ramie|umiesnione lewe ramie|pysk|widmowe nogi) (.*), zostawiajac brzydka, poszarpana rane.' _zabkowany_ktos_kogos_5 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 5/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' wbija zabkowany zakrzywiony sztylet gleboko w cialo (.*), a stalowe zeby na ostrzu broni dra tkanki ofiary, gdy wyszarpuje ja gwaltownie.' _zabkowany_ktos_kogos_6 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 6/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t' plynnym ruchem obraca w dloni zabkowany zakrzywiony sztylet, by zadac (.*) mordercze uderzenie od gory, nieomal (go|ja|je) rozplatujac.' _zabkowany_ktos_kogos_7 = /substitute -p @{BCwhite}-------> @{Cyellow}[Zabkowany 7/7] @{Cyellow}%{PL} @{Cwhite}dziabie @{Cblue}%{P1}@{Cwhite}.

#######################################################################################################################################################

; Dlugi zabkowany topor
; Aktualizacja: 04.09.12
; Ja kogoś

/def -p200 -mregexp -t'Mocnym wymachem dlugiego zabkowanego topora bitewnego usilujesz dosiegnac cialo (.*), lecz twoj przeciwnik umiejetnie zbija to uderzenie (.*).' _zabkowany_topor_ja_kogos_0_v2 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 0/7] @{Cwhite}probuje specowac @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Zgrabny unik (.*) sprawia, ze ostrze twojego dlugiego zabkowanego topora bitewnego omija [^ ]+ w bezpiecznej odleglosci.' _zabkowany_topor_ja_kogos_0 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 0/7] @{Cwhite}probuje specowac @{Cblue}%{P1}@{Cwhite}.
/eval /def -p200 -mregexp -t'Spokojnym, precyzyjnie wymierzonym uderzeniem dlugiego zabkowanego topora bitewnego zadrapujesz %{hitlocs} (.*).' _zabkowany_topor_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 1/7] @{Cwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/def -p200 -mregexp -t'Zebate ostrze dlugiego zabkowanego topora bitewnego przecina skore i zadrapuje cialo (.*), gdy celnym uderzeniem udaje ci sie trafic [^ ]+ w (.*).' _zabkowany_topor_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 2/7] @{Cwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Szybkim wypadem zupelnie zaskakujesz swego przeciwnika. Korzystajac z powstalej okazji, silnie uderzasz (.*) w (.*) dlugim zabkowanym toporem bitewnym, pozostawiajac paskudnie rozorane przeciecia.' _zabkowany_topor_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 3/7] @{Cwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Zachodzac przeciwnika od boku, mocno uderzasz (.*) dlugim zabkowanym toporem bitewnym w (.*). Ostrze gladko przecina skore, pozostawiajac gleboka, poszarpana rane.' _zabkowany_topor_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 4/7] @{Cwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Cofasz sie nieznacznie, by po chwili blyskawicznie wyskoczyc do ataku i silnie uderzyc (.*) dlugim zabkowanym toporem bitewnym w (.*). Cios pozostawia po sobie poszarpana, silnie broczaca krwia rane.' _zabkowany_topor_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 5/7] @{Cwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Dostrzegajac oslabienie (.*), wykonujesz serie szybkich acz silnych razow dlugim zabkowanym toporem bitewnym, ktore trafiaja [^ ]+ w (.*), pozostawiajac po sobie glebokie, poszarpane rany.' _zabkowany_topor_ja_kogos_6 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 6/7] @{Cwhite}specuje @{Cblue}%{P1}@{Cwhite}.
/def -p200 -mregexp -t'Markujac pare uderzen, szukasz luk w obronie (.*). Gdy dostrzegasz slabosc, wyskakujesz szybko do przodu, by z obszernego zamachu dlugim zabkowanym toporem bitewnym poteznie uderzyc swego przeciwnika w (.*), natychmiast powalajac [^ ]+ na ziemie.' _zabkowany_topor_ja_kogos_7 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 7/7] @{Cwhite}specuje @{Cblue}%{P1}@{Cwhite}.

#######################################################################################################################################################

; poreczny polkulisty topor bojowy
; Aktualizacja: 14.09.12
; Ja kogoś
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym, lecz twemu przeciwnikowi udaje sie odbic ten cios (.*).' _pulkulisty_ja_kogos_0_odbite = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 0/7] @{BCwhite}probuje specowac @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym, jednak twemu przeciwnikowi udaje sie odskoczyc.' _pulkulisty_ja_kogos_0_unik = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 0/7] @{BCwhite}probuje specowac @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym, ale twemu przeciwnikowi udaje sie sparowac ten cios (.*).' _pulkulisty_ja_kogos_0_odbite_v2 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 0/7] @{BCwhite}probuje specowac @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym w (.*), zaledwie muskajac.' _pulkulisty_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 1/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym w (.*), czyniac niewielka ranke.' _pulkulisty_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 2/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym w (.*), pozostawiajac wyrazna rane.' _pulkulisty_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 3/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym w (.*), dosc powaznie (tnac|klujac).' _pulkulisty_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 4/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym w (.*), bardzo powaznie raniac.' _pulkulisty_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 5/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym w (.*), pozostawiajac paskudnie wygladajaca, (kluta|cieta) rane.' _pulkulisty_ja_kogos_6 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 6/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
/def -p200 -mregexp -t'(Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz|Przestepujesz w bok, by z silnego zamachu uderzyc|Przez chwile rozwazasz najlepszy sposob na atak, by wreszcie szybkim ruchem uderzyc zza lewego ucha|Nagle wyskakujesz do przodu, by z szerokiego wymachu uderzyc|Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc) (.*) porecznym polkulistym toporem bojowym. Twa bron (.*)' _pulkulisty_ja_kogos_7 = /substitute -p @{BCwhite}----> @{Cyellow}[Toporek 7/7] @{BCwhite}specuje @{Cblue}%{P2}@{Cwhite}.
;Dostrzegajac szanse na dogodny atak, gwaltownym ruchem uderzasz (.*) porecznym polkulistym toporem bojowym. Twa bron zaglebia sie w jego cialo, rozrywajac tkanki i czyniac ogromne spustoszenie. Gdy silnym szarpnieciem wyrywasz topor z cielska przeciwnika, przez twarz trolla przebiegaja rozne emocje - bol, zdziwienie, przerazenie, by ostatecznie stezec w pustym, pozbawionym zycia wyrazie.
;Wykonujesz pare markowanych wymachow, by wreszcie jednym z nich uderzyc brazowego duzego bobolaka porecznym polkulistym toporem bojowym w nogi, zaledwie muskajac.

#######################################################################################################################################################

; misterny obosieczny topor
; Ja kogoś

/eval /def -p200 -mregexp -t'Z oszczednego zamachu uderzasz swym misternym obosiecznym toporem w %{hitlocs} (.*), znaczac ostrze broni kilkoma kroplami krwi.' _misterny_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 1/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Twoj misterny obosieczny topor zahacza o %{hitlocs} (.*), (pozostawiajac plytka, nierowna rane|zadajac nieduze obrazenia).' _misterny_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 2/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Z szerokiego zamachu tniesz misternym obosiecznym toporem w %{hitlocs} (.*), (a tryskajaca z tej rany krew zrasza ziemie.|raniac [^ ]+.)' _misterny_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 3/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Rozpedzone ostrze dzierzonego przez ciebie misternego obosiecznego topora bezlitosnie wbija sie w %{hitlocs} (.*), (zadajac [^ ]+ ciezka rane|ciezko [^ ]+ raniac).' _misterny_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 4/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Przy akompaniamencie oszalamiajacego syku przecinanego powietrza krwawe ostrze twego misternego obosiecznego topora (wrzyna sie|godzi) w %{hitlocs} (.*), (odrzucajac [^ ]+ w tyl niczym szmaciana lalke.|zadajac ogromne obrazenia!)' _misterny_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 5/7] @{BCwhite}specuje @{Cblue}%%{P3}@{Cwhite}.
/eval /def -p200 -mregexp -t'Druzgoczacym atakiem misternego obosiecznego topora brutalnie rozcinasz %{hitlocs} (.*), zatrzymujac ped swej morderczej broni dopiero wtedy, kiedy zbrukane posoka ostrze grzeznie pomiedzy koscmi ofiary.' _misterny_ja_kogos_6 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 6/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Szybkim wypadem wymijasz (.*) i wykorzystujac rozpedzona mase swego misternego obosiecznego topora bez trudu wyprowadzasz w pedzie dwa smiertelne ciosy.' _misterny_ja_kogos_7 = /substitute -p @{BCwhite}----> @{Cyellow}[Misterny 7/7] @{BCwhite}specuje @{Cblue}%%{P1}@{Cwhite}.


/eval /def -p200 -mregexp -t'Ostrym jak sztylet gornym szpikulcem sterczacym ze styliska misternego obosiecznego topora godzisz (.*) w (.*), spuszczajac [^ ]+ nieco krwi.' _misterny_plus_ja_kogos_1 = /substitute -p @{BCwhite}----> @{Cyellow}[Mister+ X/7] @{BCwhite}specuje @{Cblue}%%{P1}@{Cwhite}.
/eval /def -p200 -mregexp -t'Naglym pchnieciem wbijasz sterczacy z nasady zelezca misternego obosiecznego topora kolec w %{hitlocs} (.*), (powodujac paskudny krwotok.|zadajac powazne obrazenia.)' _misterny_plus_ja_kogos_2 = /substitute -p @{BCwhite}----> @{Cyellow}[Mister+ X/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Korzystajac z nadarzajacej sie okazji, gwaltownym uderzeniem styliska misternego obosiecznego topora wbijasz sterczacy zen szpic w %{hitlocs} (.*), pozostawiajac gleboka rane.' _misterny_plus_ja_kogos_3 = /substitute -p @{BCwhite}----> @{Cyellow}[Mister+ X/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Szybkim ciosem jednego ze szpikulcow misternego obosiecznego topora uderzasz w %{hitlocs} (.*), pozostawiajac niewielkie zadrapanie.' _misterny_plus_ja_kogos_4 = /substitute -p @{BCwhite}----> @{Cyellow}[Mister+ X/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Z impetem wyrzucasz przed siebie misterny obosieczny topor, idealnie wymierzajac cios gornego szpica w %{hitlocs} (.*), bardzo ciezko [^ ]+ raniac' _misterny_plus_ja_kogos_5 = /substitute -p @{BCwhite}----> @{Cyellow}[Mister+ X/7] @{BCwhite}specuje @{Cblue}%%{P2}@{Cwhite}.
/eval /def -p200 -mregexp -t'Szybki niczym atak kobry cios gornego szpikulca sterczacego z twojego misternego obosiecznego topora z mordercza sila trafia (.*) w (.*), momentalnie pozbawiajac [^ ]+ zycia. Bezwladne cialo pada u twych stop, wciaz jeszcze broczac krwia ze smiertelnej rany.' _misterny_plus_ja_kogos_7 = /substitute -p @{BCwhite}----> @{Cyellow}[Mister+ 7/7] @{BCwhite}specuje @{Cblue}%%{P1}@{Cwhite}.
